# Automated dependency update configuration
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates

version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "10:00"
    reviewers:
      - "ColeMorton"
    assignees:
      - "ColeMorton"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    open-pull-requests-limit: 5
    target-branch: "main"
    labels:
      - "dependencies"
      - "python"
    ignore:
      # Ignore major version updates for core dependencies
      - dependency-name: "pandas"
        update-types: ["version-update:semver-major"]
      - dependency-name: "numpy"
        update-types: ["version-update:semver-major"]
      - dependency-name: "scikit-learn"
        update-types: ["version-update:semver-major"]

  # Frontend dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "11:00"
    reviewers:
      - "ColeMorton"
    assignees:
      - "ColeMorton"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    open-pull-requests-limit: 5
    target-branch: "main"
    labels:
      - "dependencies"
      - "frontend"
      - "typescript"
    ignore:
      # Ignore major version updates for framework dependencies
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      - dependency-name: "astro"
        update-types: ["version-update:semver-major"]

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "ColeMorton"
    assignees:
      - "ColeMorton"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
