[build]
  publish = "dist"
  command = "yarn build"

[[plugins]]
  package = "@astrojs/netlify"

[functions]
  directory = "netlify/functions"

# Form notifications
[[form]]
  name = "contact"
  action = "/contact-success"

  [form.settings]
    send_confirmation = true
    confirmation_template = "contact-confirmation"

  [[form.notification]]
    type = "email"
    event = "submission"
    to = "cole.morton@hotmail.com"
    subject = "New Contact Form Submission - Cole Morton Website"
    body = """
    You have received a new contact form submission:

    Name: {{name}}
    Email: {{email}}
    Message: {{message}}

    Submitted at: {{created_at}}
    """
