[build]
  publish = "dist"
  command = "yarn build"

[build.environment]
DISABLE_PYTHON = "true"
DISABLE_MISE = "true"


[functions]
  directory = "netlify/functions"

# Form notifications
[[form]]
  name = "contact"
  action = "/contact-success"

  [form.settings]
    send_confirmation = true
    confirmation_template = "contact-confirmation"

  [[form.notification]]
    type = "email"
    event = "submission"
    to = "${CONTACT_EMAIL}"
    subject = "${CONTACT_NOTIFICATION_SUBJECT}"
    body = """
    You have received a new contact form submission:

    Name: {{name}}
    Email: {{email}}
    Message: {{message}}

    Submitted at: {{created_at}}
    """
