[build]
base = "frontend"
publish = "frontend/dist"
command = "yarn build"
ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."

[build.environment]
NODE_VERSION = "20"
PYTHON_VERSION = "3.8"

[context.staging]
command = "yarn build"
environment = { NODE_ENV = "staging" }

[context.production]
command = "yarn build"
environment = { NODE_ENV = "production" }
