[build]
base = "frontend"
publish = "dist"
command = "rm -rf node_modules && NODE_ENV=development yarn install && yarn build"
ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."

[build.environment]
NODE_VERSION = "20"
DISABLE_PYTHON = "true"

[context.staging]
command = "rm -rf node_modules && NODE_ENV=development yarn install && yarn build"
environment = { NODE_ENV = "staging" }

[context.production]
command = "rm -rf node_modules && NODE_ENV=development yarn install && yarn build"
environment = { NODE_ENV = "production", PUBLIC_FEATURE_CALCULATORS = "false" }
