# Production Environment Configuration

global:
  cache:
    ttl_seconds: 900  # 15 minutes
    max_size_mb: 500  # Larger cache for production

  rate_limiting:
    enabled: true

  request:
    timeout_seconds: 45  # Longer timeout for production
    max_retries: 5  # More retries for reliability

  logging:
    level: INFO

services:
  yahoo_finance:
    cache:
      ttl_seconds: 600  # 10 minutes

  alpha_vantage:
    rate_limit:
      requests_per_minute: 5  # Respect API limits

  fred:
    cache:
      ttl_seconds: 7200  # 2 hours

  sec_edgar:
    rate_limit:
      requests_per_minute: 10
    timeout_seconds: 60  # Longer timeout for SEC

  fmp:
    rate_limit:
      requests_per_minute: 250

  coingecko:
    rate_limit:
      requests_per_minute: 50

  imf:
    cache:
      ttl_seconds: 1800  # 30 minutes

orchestration:
  data_quality:
    min_success_rate: 0.8  # Higher requirement for production
    health_check_interval: 180  # 3 minutes

cli:
  verbose_logging: false
  auto_cache_cleanup: true
